// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mytest.proto

#include "mytest.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace example {
class myRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<myRequest>
      _instance;
} _myRequest_default_instance_;
class myResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<myResponse>
      _instance;
} _myResponse_default_instance_;
}  // namespace example
namespace protobuf_mytest_2eproto {
static void InitDefaultsmyRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::example::_myRequest_default_instance_;
    new (ptr) ::example::myRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::example::myRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_myRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmyRequest}, {}};

static void InitDefaultsmyResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::example::_myResponse_default_instance_;
    new (ptr) ::example::myResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::example::myResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_myResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmyResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_myRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_myResponse.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::ServiceDescriptor* file_level_service_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example::myRequest, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example::myRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example::myRequest, num1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example::myRequest, num2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example::myRequest, opt_),
  1,
  2,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example::myResponse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example::myResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::example::myResponse, ans_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::example::myRequest)},
  { 11, 17, sizeof(::example::myResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::example::_myRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::example::_myResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "mytest.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, file_level_service_descriptors);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014mytest.proto\022\007example\"4\n\tmyRequest\022\014\n\004"
      "num1\030\001 \002(\005\022\014\n\004num2\030\002 \002(\005\022\013\n\003opt\030\003 \002(\t\"\031\n"
      "\nmyResponse\022\013\n\003ans\030\001 \002(\0052\?\n\tmyService\0222\n"
      "\007calcute\022\022.example.myRequest\032\023.example.m"
      "yResponseB\003\200\001\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 174);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mytest.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_mytest_2eproto
namespace example {

// ===================================================================

void myRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int myRequest::kNum1FieldNumber;
const int myRequest::kNum2FieldNumber;
const int myRequest::kOptFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

myRequest::myRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_mytest_2eproto::scc_info_myRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:example.myRequest)
}
myRequest::myRequest(const myRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  opt_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_opt()) {
    opt_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.opt_);
  }
  ::memcpy(&num1_, &from.num1_,
    static_cast<size_t>(reinterpret_cast<char*>(&num2_) -
    reinterpret_cast<char*>(&num1_)) + sizeof(num2_));
  // @@protoc_insertion_point(copy_constructor:example.myRequest)
}

void myRequest::SharedCtor() {
  opt_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&num1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&num2_) -
      reinterpret_cast<char*>(&num1_)) + sizeof(num2_));
}

myRequest::~myRequest() {
  // @@protoc_insertion_point(destructor:example.myRequest)
  SharedDtor();
}

void myRequest::SharedDtor() {
  opt_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void myRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* myRequest::descriptor() {
  ::protobuf_mytest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mytest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const myRequest& myRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_mytest_2eproto::scc_info_myRequest.base);
  return *internal_default_instance();
}


void myRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:example.myRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    opt_.ClearNonDefaultToEmptyNoArena();
  }
  if (cached_has_bits & 6u) {
    ::memset(&num1_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&num2_) -
        reinterpret_cast<char*>(&num1_)) + sizeof(num2_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool myRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:example.myRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 num1 = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_num1();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 num2 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_num2();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string opt = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_opt()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->opt().data(), static_cast<int>(this->opt().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "example.myRequest.opt");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:example.myRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:example.myRequest)
  return false;
#undef DO_
}

void myRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:example.myRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 num1 = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num1(), output);
  }

  // required int32 num2 = 2;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->num2(), output);
  }

  // required string opt = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->opt().data(), static_cast<int>(this->opt().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "example.myRequest.opt");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->opt(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:example.myRequest)
}

::google::protobuf::uint8* myRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:example.myRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 num1 = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num1(), target);
  }

  // required int32 num2 = 2;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->num2(), target);
  }

  // required string opt = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->opt().data(), static_cast<int>(this->opt().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "example.myRequest.opt");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->opt(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:example.myRequest)
  return target;
}

size_t myRequest::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:example.myRequest)
  size_t total_size = 0;

  if (has_opt()) {
    // required string opt = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->opt());
  }

  if (has_num1()) {
    // required int32 num1 = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num1());
  }

  if (has_num2()) {
    // required int32 num2 = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num2());
  }

  return total_size;
}
size_t myRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:example.myRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string opt = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->opt());

    // required int32 num1 = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num1());

    // required int32 num2 = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num2());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void myRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:example.myRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const myRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const myRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:example.myRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:example.myRequest)
    MergeFrom(*source);
  }
}

void myRequest::MergeFrom(const myRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:example.myRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_opt();
      opt_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.opt_);
    }
    if (cached_has_bits & 0x00000002u) {
      num1_ = from.num1_;
    }
    if (cached_has_bits & 0x00000004u) {
      num2_ = from.num2_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void myRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:example.myRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void myRequest::CopyFrom(const myRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:example.myRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool myRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void myRequest::Swap(myRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void myRequest::InternalSwap(myRequest* other) {
  using std::swap;
  opt_.Swap(&other->opt_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(num1_, other->num1_);
  swap(num2_, other->num2_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata myRequest::GetMetadata() const {
  protobuf_mytest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mytest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void myResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int myResponse::kAnsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

myResponse::myResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_mytest_2eproto::scc_info_myResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:example.myResponse)
}
myResponse::myResponse(const myResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ans_ = from.ans_;
  // @@protoc_insertion_point(copy_constructor:example.myResponse)
}

void myResponse::SharedCtor() {
  ans_ = 0;
}

myResponse::~myResponse() {
  // @@protoc_insertion_point(destructor:example.myResponse)
  SharedDtor();
}

void myResponse::SharedDtor() {
}

void myResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* myResponse::descriptor() {
  ::protobuf_mytest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mytest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const myResponse& myResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_mytest_2eproto::scc_info_myResponse.base);
  return *internal_default_instance();
}


void myResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:example.myResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ans_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool myResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:example.myResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 ans = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_ans();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ans_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:example.myResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:example.myResponse)
  return false;
#undef DO_
}

void myResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:example.myResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 ans = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->ans(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:example.myResponse)
}

::google::protobuf::uint8* myResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:example.myResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 ans = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->ans(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:example.myResponse)
  return target;
}

size_t myResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:example.myResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required int32 ans = 1;
  if (has_ans()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->ans());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void myResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:example.myResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const myResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const myResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:example.myResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:example.myResponse)
    MergeFrom(*source);
  }
}

void myResponse::MergeFrom(const myResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:example.myResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_ans()) {
    set_ans(from.ans());
  }
}

void myResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:example.myResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void myResponse::CopyFrom(const myResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:example.myResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool myResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void myResponse::Swap(myResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void myResponse::InternalSwap(myResponse* other) {
  using std::swap;
  swap(ans_, other->ans_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata myResponse::GetMetadata() const {
  protobuf_mytest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mytest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

myService::~myService() {}

const ::google::protobuf::ServiceDescriptor* myService::descriptor() {
  protobuf_mytest_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_mytest_2eproto::file_level_service_descriptors[0];
}

const ::google::protobuf::ServiceDescriptor* myService::GetDescriptor() {
  return descriptor();
}

void myService::calcute(::google::protobuf::RpcController* controller,
                         const ::example::myRequest*,
                         ::example::myResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method calcute() not implemented.");
  done->Run();
}

void myService::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), protobuf_mytest_2eproto::file_level_service_descriptors[0]);
  switch(method->index()) {
    case 0:
      calcute(controller,
             ::google::protobuf::down_cast<const ::example::myRequest*>(request),
             ::google::protobuf::down_cast< ::example::myResponse*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& myService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::example::myRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& myService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::example::myResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

myService_Stub::myService_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
myService_Stub::myService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
myService_Stub::~myService_Stub() {
  if (owns_channel_) delete channel_;
}

void myService_Stub::calcute(::google::protobuf::RpcController* controller,
                              const ::example::myRequest* request,
                              ::example::myResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace example
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::example::myRequest* Arena::CreateMaybeMessage< ::example::myRequest >(Arena* arena) {
  return Arena::CreateInternal< ::example::myRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::example::myResponse* Arena::CreateMaybeMessage< ::example::myResponse >(Arena* arena) {
  return Arena::CreateInternal< ::example::myResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
